version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "verdaccio-aws-sam"
s3_bucket = "dnw-templates-2022"
s3_prefix = "verdaccio-aws-sam"
region = "ap-southeast-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = false
image_repositories = []
