AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-sam-test

  Sample SAM Template for aws-sam-test
Resources:
  ApiFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: "aws-sam-test"
      CodeUri: publish/
      Handler: index.lambdaHandler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      MemorySize: 256
      Timeout: 10
      Policies:
        - AWSLambda_FullAccess
      Events:
        ProxyResource:
          Type: HttpApi
          Properties:
            Path: /{name}
            Method: any

Outputs:
  ApiUrl:
    Description: "API endpoint URL for Prod environment"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
