version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "api-ts"
s3_bucket = "dnw-templates-2022"
s3_prefix = "api-ts"
region = "ap-southeast-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
